INSERT INTO `USER` (`ID`, `USER_NAME`, `PASSWORD`) VALUES (1, 'admin', '$2a$10$lW9Q6thFdccwPiRyOmQmreEtNhERoYGEsYKRL3uV97Q9u2ZGKxusW');
INSERT INTO `USER` (`ID`, `USER_NAME`, `PASSWORD`) VALUES (2, 'Jancsi16', '$2a$10$lW9Q6thFdccwPiRyOmQmreEtNhERoYGEsYKRL3uV97Q9u2ZGKxusW');
INSERT INTO `USER` (`ID`, `USER_NAME`, `PASSWORD`) VALUES (3, 'Icuka', '$2a$10$lW9Q6thFdccwPiRyOmQmreEtNhERoYGEsYKRL3uV97Q9u2ZGKxusW');
INSERT INTO `USER` (`ID`, `USER_NAME`, `PASSWORD`) VALUES (4, 'Aladdin98', '$2a$10$lW9Q6thFdccwPiRyOmQmreEtNhERoYGEsYKRL3uV97Q9u2ZGKxusW');